### PR TITLE
add analyze_multi feature, update tests+docs

### PR DESCRIPTION
**Pull request by mwkling**
Redoing all the work to generate the stats/data for use in the scoring function seemed like a waste of resources if you wanted to get (e.g.) Flesch-Kincaid Grade Level as well as Reading Ease scores for the same document.  I've tried to add support for performing multiple analyses that avoids this duplicated effort and updated tests/docs to reflect this.  Cheers!

### CODE REVIEW

**Comment by cameronsutter** [comment]
That sounds like a really valuable use case. The output feels a little confusing. Another way to achieve the same performance gains would be to cache the analysis within the instance and then when a second scoring function is called you don't have to run the whole thing again. Does that feel like it gets at what you were hoping for?

**Comment by mwkling** [comment]
I think what you're describing is close to what I'm doing now.  Odyssey::Engine is caching the analysis in the @data and @stats instance variables, and Odyssey.analyze_multi does the work of creating the engine, updating the formulas and calculating the scores.

As currently implemented, I expected a typical user would be calling Odyssey.analyze or one of the Odyssey.formula_name methods, and not working directly with an instance of Odyssey::Engine.

Maybe there could be a cache, built as a hash from input text to an Odyssey::Engine instance, and if self.analyze is called again for the same text it uses the existing engine instance and skips analysis?   It feels slightly weird to me having the input text (potentially large document) acting as a hash key, and introduces a hash lookup that's not currently necessary in analyze_multi.

What do you find confusing about the output?  Providing a list as input and returning a hash of formula_name => score seemed like the simplest output option.

Thanks for the quick response!

**Comment by cameronsutter** [comment]
I see your point. You're right that you're already caching and making the input text a hash key does not sound like a good idea.

With all_stats false you're right that the output is very straightforward and simple. But with all_stats true it's a little confusing. Can you give an example?

**Comment by mwkling** [comment]
Right now with `all_stats = true`, I would imagine usage as:
`scores, stats = Odyssey.analyze_multi(text, formula_names, true)`

`scores` will be the same Hash as when all_stats is set to false.  `stats` will be the same Hash returned when all_stats is set to true for `Odyssey.analyze`.  A little awkwardly, the name and formula_class will be set to the last formula in the `formula_names` list provided.

I agree this is not great.  What if instead, `Odyssey.analyze_multi` returned a single Hash, with elements of:

```
{
  'scores'                     => Hash,
  'string_length'              => Fixnum,
  'letter_count'               => Fixnum,
  'syllable_count'             => Fixnum,
  'word_count'                 => Fixnum,
  'sentence_count'             => Fixnum,
  'average_words_per_sentence' => Float,
  'average_syllables_per_word' => Float
}
```

where `scores` is just the Hash returned when `all_stats = false`

**Comment by cameronsutter** [comment]
That looks really great to me. Let's do that!

**Comment by mwkling** [comment]
I think the changes I pushed reflect what I suggested for `all_stats = true`.  I updated the tests/readme as well.  Let me know what you think!

**Pull request merged**
